#pragma once
#include "WeaveUtils/GlobalUtils.hpp"
#include <string>
#include <string_view>
#include "internal/DeltaUtils.hpp"
#include "DynamicCollections.hpp"
#include "WeaveUtils/Stopwatch.hpp"
#include "WeaveUtils/Span.hpp"
#include "WeaveUtils/TextBlock.hpp"
#include "DataBufferHandle.hpp"
#include "TextUtils.hpp"
#include "WeaveUtils/WeaveException.hpp"